vms:
  - type: testserver
    name: "nicktest"

    cpu: 2   
    memory: 4096MB

    network:
      ip: 192.168.23.26
      netmask: 255.255.255.0
      gateway: 192.168.23.254
      dns: 192.168.0.17,192.168.0.18
      
#    network_switch: 'External Virtual Switch'
    network_switch: 'Cisco VIC Ethernet Interface #6 - Virtual Switch'
    vlanid: 1113 
 
#   source-image
    src_vhd: 'Z:\volumes\devops\devopssysprep\devopssysprep.vhdx'

#   destination will be created in Z:\\volumes\servername\servername.vhdx by default
#   to change the paths you need to updaet the prov_vm.yml first three task paths
  
