---
- name: Create directory structure
  ansible.windows.win_file:
    path: 'Z:\\volumes\\devops\{{item.name}}'
    state: directory
  with_items: "{{ vms }}"
  register: path


- name: Check whether vhdx already exists
  win_stat:
    path: 'Z:\\volumes\\devops\{{item.name}}\{{item.name}}.vhdx'
    get_checksum: false
    get_md5: false
  with_items: "{{ vms }}"
  register: file_info

#- debug: var=file_info.results


- name: Clone vhdx 
  win_copy:
    src: "{{item.item.src_vhd}}"
    dest: 'Z:\\volumes\\devops\{{item.item.name}}\{{item.item.name}}.vhdx'
    remote_src: True
  with_items: "{{ file_info.results }}"
  when: item.stat.exists == false
  register: clone

#- debug:
#    var: clone

- set_fact:
    path_folder: "{{ clone.results[0].item.invocation.module_args.path }}"

- debug: var=path_folder

- set_fact:
    page_folder: "{{ clone.results[0].item.invocation.module_args.path | win_dirname}}"

- debug: var=page_folder

     
- name: Create VMs
  win_hyperv_guest:
    name: "{{item.name}}"
    generation: "{{defaut_generation}}"
    cpu: "{{item.cpu}}"
    memory: "{{item.memory}}"
    network_switch: "{{item.network_switch}}"
    diskpath: "{{ path_folder }}"
    state: present
  with_items: "{{ vms }}"
  register: new_vms

#- debug: var=new_vms.results

- name: Set SmartPaging File Location for new Virtual Machine to use destination image path
  win_shell: Set-VM {{ item.name }} -SmartPagingFilePath {{page_folder}}
  with_items: "{{ vms }}"
  register: pagefile


- name: Set Network VlanID
  win_shell: Set-VMNetworkAdapterVlan -VMName {{item.name}} -Access -VlanId {{item.vlanid}}
  with_items: "{{ vms }}"
  register: vlanid

#- debug:
#    var: vlanid
  
- name: Configure VMs IP
  win_hyperv_guest_config_net:
    name: "{{item.name}}"
    ip: "{{item.network.ip}}" 
    netmask: "{{item.network.netmask}}"
    gateway: "{{item.network.gateway}}"
    dns: "{{item.network.dns}}"
    type: static
  with_items: "{{ vms }}"

#- debug: var=new_vms.results

- add_host:
    name: "{{ item.item.network.ip }}"
    ansible_connection: winrm
    ansible_host: "{{ item.item.network.ip }}"
    groups: "{{item.item.type}}" 
  with_items: "{{ new_vms.results }}"

#- debug: var=groups
#- debug: var=play_hosts

- name: Poweron VMs
  win_hyperv_guest:
    name: "{{item.name}}"
    state: started 
  with_items: "{{ vms }}"

#this works perfectly
- name: Wait for VM to be running
  wait_for:
    host: "{{ item.network.ip }}"
    port: "{{ ansible_port }}" 
    timeout: 100
  with_items: "{{ vms }}"
  delegate_to: localhost
  register: wait

# - debug:
#     var: wait
